### ISSUE TITLE
Let a human review Renovate's config migration PRs, instead of auto-approving

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate-approve-bot#105]
The `renovate-approve-bot` automatically approves Renovate's configuration migration PRs. I think we should let our users review the changes themselves instead of auto-approving.

Right now the configuration migration PRs makes some whitespace and ordering changes, so the PR probably needs to be fixed up by the user anyways.

To summarize: disable `renovate-approve-bot` approval for Renovate config PRs.

**Comment by rarkins** [comment]
I thought we should only approve ones marked as Automerge enabled anyway

**Comment by rarkins** [comment]
So why does it think it's automerging?

**Comment by HonkingGoose** [comment]
I found this quote from you in another discussion:

> Essentially it looks for "Automerge: enabled" in the PR body content and approves only if it sees that (otherwise it would just add noise)

https://github.com/renovatebot/renovate/discussions/15123#discussioncomment-2616982

**Comment by rarkins** [comment]
Yeah, we look for the absence of "merge this manually"

**Comment by rarkins** [comment]
Implemented
