### ISSUE TITLE
We need third approver.

### ISSUE THREAD

**Issue by DariuszLuber** [renovatebot/renovate-approve-bot#178]
Currently, there are two Renovate Approve apps available on GitHub:
- Renovate Approve
- Renovate Approve 2

We need to have third, how we can get "Renovate Approve 3" 😅

Best regards

**Comment by rarkins** [comment]
https://www.theonion.com/fuck-everything-were-doing-five-blades-1819584036

**Comment by rarkins** [comment]
It's been years since I set these 2 up, I'll see if I can add another

**Comment by rarkins** [comment]
Can you see if https://github.com/apps/renovate-approve-3 works for you? Remember that approvals are only triggered for _new_ PRs.

**Comment by maciej-wolak** [comment]
Renovate Approve 3 is a private repo :)

**Comment by rarkins** [comment]
Please try again now

**Comment by maciej-wolak** [comment]
It works perfectly! Thanks! 🥇 

![image](https://github.com/renovatebot/renovate-approve-bot/assets/112616486/0e364056-3455-40a0-8d2d-e70c8fd20532)

**Comment by DariuszLuber** [comment]
Thanks, works like a charm 👍
