### ISSUE TITLE
Is there any reason to use this rather than renovatebot's autoApprove functionality?

### ISSUE THREAD

**Issue by jfly** [renovatebot/renovate-approve-bot#197]
https://docs.renovatebot.com/configuration-options/#autoapprove

**Comment by rarkins** [comment]
Yes, GitHub doesn't allow auto approve.

**Comment by jfly** [comment]
@rarkins, I don't understand. What do you mean by GitHub doesn't allow auto approve?

**Comment by rarkins** [comment]
GitHub doesn't let users or bots approve their own PRs.

You're asking question about a GitHub-only bot, asking to compare it to a feature which isn't valid for GitHub!

**Comment by jfly** [comment]
Ahh, ok. But GitHub does allow bots to approve PRs created by a different bot? That makes sense.

**Comment by rarkins** [comment]
Yes, hence why this second bot type exists
