### ISSUE TITLE
[renovate-approve] Don't approve PRs whose checks fail

### ISSUE THREAD

**Issue by simoneb** [renovatebot/renovate-approve-bot#22]
### Which Renovate are you using? x the right box:

- [ ] Renovate Open Source CLI
- [X] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [X] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [ ] Azure DevOps

### What would you like to do?

I have the renovate-approve BOT enabled and I'm noticing that it's approving PRs even when the status checks (like our CI status check) is red. I wouldn't expect the BOT to approve PRs whose status checks are not green. Is there a way to configure this?

**Comment by rarkins** [comment]
The only reason for Renovate Approve is to allow Renovate to automerge its own PRs when PR reviews are required. Renovate won't automerge if a PR is failing, even if it's approved. Is there a problem/risk I'm missing?

**Comment by simoneb** [comment]
Probably not, it's just unusual to see a PR with broken checks approved by anybody (including BOTS), I guess.

**Comment by rarkins** [comment]
I think it's more work that the benefit. Listening to new types of webhooks, querying the combined branch status, removing approvals if they go from pass to fail, caring about which status checks are mandatory vs which are optional, etc.

**Comment by simoneb** [comment]
Ok sure, I don't have enough context to say whether it makes sense or not in terms of effort.
