### ISSUE TITLE
Have a second approval bot

### ISSUE THREAD

**Issue by DiegoRBaquero** [renovatebot/renovate-approve-bot#25]
I would like to require 2 reviewers, but that would mean renovate-approve alone is not enough.

Is there a way to have 2 of these bots?

**Comment by mikaelkolkinn** [comment]
We are in this situation too. Any ideas? @rarkins

**Comment by DiegoRBaquero** [comment]
> We are in this situation too. Any ideas? @rarkins

I created: https://github.com/apps/weighted-reviews and assigned 50 points by default (so 2 reviews per PR) and renovate-approve[bot] 100 points. It's been working perfectly for 2 weeks.

**Comment by mikaelkolkinn** [comment]
Interesting @DiegoRBaquero. Might check it out, thanks.

**Comment by rarkins** [comment]
Can you check if https://github.com/apps/renovate-approve-2 works for you? Remember you will probably need a *new* automerging PR to see it in action. I haven't tried it myself yet

**Comment by mikaelkolkinn** [comment]
Worked like a charm. Thank you @rarkins!
