### ISSUE TITLE
Can I use renovate-approve-bot for Java, Python and Docker 

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [renovatebot/renovate-approve-bot#37]
I have few questions, as I am new to renovate. Kindly assist.

Can I use renovate-approve for Java, Python and Docker ?

I reason I have this question is because [package.json](https://github.com/renovatebot/renovate-approve-bot/blob/09ac685676e694837d84602e55a669cb1eaf5b84/Dockerfile#L19) is used in dockerfile

If available, Please provide the detailed documentation as to how to build the dockerfile and deploy in OCP.  We have renovate already on OCP from other team, how to integrate approve bot to make it work with renovate ?

**Comment by rarkins** [comment]
This is a JS bot and can run inside Docker or not. 

The languages you can automerge are independent of what language the bot is written in.

**Comment by rarkins** [comment]
You're free to use this but I don't have time to write any beginner guides
