### ISSUE TITLE
Using `renovate-approve` with self-hosted renovate

### ISSUE THREAD

**Issue by caseydialpad** [renovatebot/renovate-approve-bot#41]
First off, both `renovate` and `renovate-approve` are fantastic tools! Thank you!

I am looking to use renovate-approve-bot with a self-hosted renovate-bot deployment. Is there a simple way to configure `renovate-approve` to approve changes created by our `renovate` user (our user is a Github user)?

If I am understanding the code base, it appears that it the `process.env.RENOVATE_BOT_USER` variable is configurable to new usernames (though it looks like it pulls that from the deployment's environment).

Is it simply the case I will need to self-host the `renovate-approve` bot in a private app to configure that setting? If so, would you be able to provide some guidance on running it in a private app?

**Comment by rarkins** [comment]
You will need to run your own renovate approve bot if you have your own renovate. It is event-driven (responding to webhooks) and we run the official one on glitch.me. It's basically a copy of the files in this repo plus the app private key and env variables: 
![image](https://user-images.githubusercontent.com/6311784/102464664-ec3c5080-404c-11eb-8e39-2a8d9d04dec2.png)

**Comment by caseydialpad** [comment]
Thank you. I'm experimenting with it now.

**Comment by caseydialpad** [comment]
I was able to get a self-hosted `renovate-approve-bot` working. Thank you.
