### ISSUE TITLE
renovate-approve-bot-2 not opening reviews anymore

### ISSUE THREAD

**Issue by carlobeltrame** [renovatebot/renovate-approve-bot#42]
Since approximately yesterday at noon GMT, renovate-approve-bot 2 does not open any reviews on our repository https://github.com/ecamp/ecamp3 anymore. I already tried re-installing the bot, and renovate has opened a new PR since then, but approve-bot 2 seems to be on vacation. Do you have any insights on this?

Strangely, it first stopped working on https://github.com/ecamp/ecamp3/pull/865 but still worked on https://github.com/ecamp/ecamp3/pull/864 two hours later.

We have recently changed the renovate config in https://github.com/ecamp/ecamp3/pull/854, maybe it's something to do with that. However, renovate itself works perfectly fine.

**Comment by rarkins** [comment]
It's hosted on Glitch (boosted i.e. paid) but unfortunately is entirely unresponsive so I have raised a support request. I don't think it's meant to ever be *this* down:

![image](https://user-images.githubusercontent.com/6311784/105991670-62988d80-60a4-11eb-8b9a-7328dc42c209.png)

Also the first approve account is identical code and hosted on the same Glitch account.. and is fine

**Comment by rarkins** [comment]
I brought up a duplicate app and it seems to be doing the job now - e.g. see this PR: https://github.com/renovatebot/renovate/pull/8435

Will close this now, thanks for alerting us to the problem

**Comment by carlobeltrame** [comment]
Thanks for acting so fast, I can confirm it works again.
