### ISSUE TITLE
approve-2 not working anymore

### ISSUE THREAD

**Issue by carlobeltrame** [renovatebot/renovate-approve-bot#60]
Hi! On our repo https://github.com/ecamp/ecamp3/pulls, renovate approve bot 1 works perfectly, but approve bot 2 has stopped doing anything about a week ago. I have tried removing it from the repository completely and re-installing it, but that didn't help so far. Any ideas what's wrong?

**Comment by rarkins** [comment]
The automerging PRs all seem to have two approvals: 
![image](https://user-images.githubusercontent.com/6311784/123073202-80310f80-d416-11eb-80dd-12769b6024b5.png)

**Comment by carlobeltrame** [comment]
Yes, it started working again this morning. Thanks anyways!
