### ISSUE TITLE
not adding approvals for replacements PRs

### ISSUE THREAD

**Issue by travi** [renovatebot/renovate-approve-bot#78]
i've started configuring replacements within a private project that has approval requirements. while the approval bots have been working well for dependency update PRs, i noticed that approvals were not added to replacement PRs.

is this an intentional limitation? if it is unexpected, what details could i provide that would be helpful?

**Comment by rarkins** [comment]
All they look for is text in the PR body saying that automerge is enabled, so it shouldn't care whether it's a replacement or not.

**Comment by travi** [comment]
ah, automerge is the issue then. since we still have to have a codeowner approve on most of the auto-approved PRs, it didnt dawn on me that the approval was tied to automerge specifically. i have that disabled for the replacements PRs, so that explains it then. thanks!
